generate controllers and views
cancelei/EsportGamingCenter_backend pull request #22
Opened 2023-12-04 12:17 UTC by Gardimy

For this milestone, I just created a basic controllers and views.

2023-12-04 15:43 UTC, alvp01 requested changes
Some changes are required

2023-12-04 15:43 UTC, alvp01 commented on config/database.yml
> +  password: gardy
Changes a required to use a general DB password (environment variables)

2023-12-04 15:43 UTC, alvp01 commented on app/views/layouts/games/inde.html.erb
View files not required, please delete them

2023-12-05 12:26 UTC, lerfast commented
### Hi  @Gardimy  👋 👋,

This PR is completed! There is nothing else to say other than... it's time to merge it 🚀👨🏼‍🚀
Congratulations! 🎉

### STATUS: APPROVED ✔✔

![nicejob](https://github.com/hafiz1379/Catalog-of-my-things/assets/45726631/01f467e2-9609-4b30-b1d0-50f35b1fd118)

🎯 TOP HIGHLIGHTS 🎯
- Cleanly written code ✅
- Working as expected ✅

2023-12-05 12:26 UTC, merged