Final group capstone - Book an Appointment
cancelei/EsportGamingCenter_backend pull request #40
Opened 2023-12-13 20:04 UTC by Gardimy

Project Description: eSports Reservation System

**Overview**

This project involves developing an eSports reservation system with two distinct parts: the Backend, developed using Ruby on Rails, and the Frontend, built with React. This system aims to cater to eSports players, allowing them to reserve games, manage reservations, and access a catalog of available games.

Database Schema (Needs a revision, since the Normal user/Admin user is not clearly depicted in the document, and can generate doubts later):

- Esport Player - CurrentUser
- Esport Game - Can reserve a Game
- Gaming Center - Catalog of Available Games + Welcome Page
- Reservation Center - List of Reservations

Page Structure: 
Navigation (when the user is logged in): 
Games Catalog, 
Games List, (admin-only)
Reservations (list with delete button per item and button to Reserve(Form)), 
Reserve (form), 
Logout.
Navigation (when the user hasn't logged in): Login + Singup.

Core Features:

Shared tasks:

1 feat/Initialize Code in the Repository and Readme Preparation
 (Front and Backend)

Run Initialization commands in Front and backend.
Front: Run the npx create-react app or similar.
	Backend: Run rails new app-name -pg –api

Add Linters for Front and Backend
Add 2 Readme File that need to be connected with each other and there should be a “main” readme file where we will put the deployment link (We chose to be the Backend Repo).

2 feat/Responsive Design

The application should be responsive, with both mobile and desktop versions efficiently designed.

3 feat/Testing and Add Linters

Each person will test their respective tasks when this task is started.
Unit Test (Models, Controllers and Views)
Integration Test (For user interactions)

— Individual Tasks: —

1 feat/ [2pt] Individual Task - User Authentication and Login

Users log in via a simple interface, inputting only their username. The user table should have Full Name, email and let Devise gem create the remaining user table-related information.

Expected result after filling in the ‘Sign In’ form, the user should be redirected to the Catalog Page.

2 feat/ [2pt] Individual Task - Game Catalog

You will create a carousel that displays a Catalog of all Games available. (With name, short details, and genre).
Displays a carousel view of available games.

3 feat/ [2pt] Individual Task - Game Detail Page

Features a full description of the selected game.
Includes a 'Reserve' button to book the game.
This task will have code implementation on the controller, model, and view.
Use each game in the catalog as link to the correct Detail Page for that Game.

3.1 feat/ [2pt] Individual Task - Reserve from Detail Page

When a user goes to the ‘Game Detail Page’ and clicks on the Reserve Button, he should be prompted to the form where his email and the selected game are “hardcoded” on the form.

The expected result is that a new Reservation appear in the Reservations List.

3.1 feat/ [2pt] Individual Task - Reserve from Navigation.

When a user clicks the Reserve (in the nav bar) he should be prompted to the form where just his email is already selected (hardcoded).
Form fields: email, Game, Setup_config, and Date (MM/DD/YYYY). 

The user should be able to select all available games from the list.

The expected result is that a new Reservation appears in the Reservations List.

4 feat/ [2pt] Individual Task - Games List
Create a list of all available games. For now, just the basic structure is needed.

It should make all the games that are available in the Catalog appear here in List format, so in future tasks, we will transform it into an “Admin-related feature”.

4 feat/ [2pt] Individual Task - Adding New Game

A form is accessible via the navigation panel for adding new games to the catalog.

After adding an item with complete information needed according to the data base schema shared on 11/29/2023. The new Game should appear in the Catalog of Games.

This task will have code implementation on the controller, model and view.

An added game should appear in the Catalog Page and the Game List page.

5 feat/ [2pt] Individual Task - Deletion of Games

When navigating in the Games List with all games each row will have an add a  'Delete' button.

This task will have code implementation on the controller, model and view.

Expected Result: A deleted game should disappear from the Catalog Page and the Game List page.

7 feat/ [2pt] Individual Task - My Reservations Page

Users can view all their reservations, with details like game name, date, and config_PC.

8 feat/ [2pt] Individual Task - API Documentation

Comprehensive documentation for the API should be provided.

9 feat/ [2pt] Individual Task - Implement Restriction for Admin-Exclusive Access

Ensure that the ‘Game List’ view and methods  'Add Game' and 'Delete Game' are accessible only to users with admin privileges.

Validate if a User can delete his own reservations.
Validate if a User can create his own reservations.

Validate if the user and the admin have different permissions related to adding and deleting games. Important: A user shouldn’t be able to delete or add a new Game to the Catalog.

10 feat/ [2pt] Individual Task - Navigation Panel

You will develop a nav bar reviewing all of the already implemented routes, and create links to redirect users to the different views available.

Includes links to:
Game Catalog (carrousel)
Games List (list for Admins to add and delete)
Reserve (form)
Reservations (list) 
Sign Out

Optional Tasks:
11/  [2pt] Individual Task - API connection with External Esports data provider

5 Team members: 

[gardimycharles889@gmail.com](mailto:gardimycharles889@gmail.com)
[jdxelric@gmail.com](mailto:jdxelric@gmail.com)
[luisemiliorojas@hotmail.com](mailto:luisemiliorojas@hotmail.com)
[abel.lavieri@gmail.com](mailto:abel.lavieri@gmail.com)
[glauber.bannwart@gmail.com](mailto:glauber.bannwart@gmail.com)

How to create a “Shared Commit” by including this in the commit message:
	In the Command Line>
-m "Commit Title" -m "Commit Description:

-  Co-authored-by: Gardimy<gardimycharles889@gmail.com>
-  Co-authored-by: JuanDiegoGuerra<jdxelric@gmail.com>
- Co-authored-by: lerfast<luisemiliorojas@hotmail.com>
- Co-authored-by: alvp01<[abel.lavieri@gmail.com](mailto:abel.lavieri@gmail.com)>
-  Co-authored-by: Cancelei<[glauber.bannwart@gmail.com](mailto:glauber.bannwart@gmail.com)>"

- VS Code Commit feature>
- **Add new feature**
- 
 ****Co-authored-by: Gardimy<gardimycharles889@gmail.com>
 Co-authored-by: JuanDiegoGuerra<jdxelric@gmail.com>
Co-authored-by: lerfast<luisemiliorojas@hotmail.com>
Co-authored-by: alvp01<[abel.lavieri@gmail.com](mailto:abel.lavieri@gmail.com)>
Co-authored-by: Cancelei<glauber.bannwart@gmail.com>****

2023-12-13 21:03 UTC, cancelei commented
@JuanDiegoGuerra we got any news from linter fixes?

2023-12-13 22:25 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Nice code organization ✔️ 
-  API is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-13 22:25 UTC, Meltrust commented on config/database.yml
> +  database: <%= ENV['DB_NAME_DEV'] %>
- [x] This project relies on a .env file that has not been pushed to the repo:

![image](https://github.com/cancelei/EsportGamingCenter_backend/assets/57421823/e63c12a5-9740-4d68-8b55-46acb80ffadb)

Kindly, provide instructions about how to set up the required .env file with all the correct properties and their values.

That way, all your users will be able to setup and run your project correctly. 👍 

_I'll create my own in order to be able to continue the review._

2023-12-13 22:25 UTC, Meltrust commented on README.md
> +```
- [ ] The ./spec/models folder does not exist.  If you are not going to include models tests, kindly remove this section of the instructions.  👍

2023-12-13 22:25 UTC, Meltrust commented on README.md
> +rspec ./spec/models
- [ ]  You are using rswag, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2023-12-13 22:25 UTC, Meltrust commented on app/controllers/api/reservations_controller.rb
> +    end
- [ ] What happens here if the reservation is not successfully destroyed?  Kindly, add some error handling like you did in the update method (line 28). 👍

2023-12-14 01:04 UTC, lerfast commented on config/database.yml
> +  database: <%= ENV['DB_NAME_DEV'] %>
![image](https://github.com/cancelei/EsportGamingCenter_backend/assets/111823606/c80bdae3-9d22-43da-960f-85a039791826)
Done!!

2023-12-14 05:09 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Superfluous test folder has been removed✔️ 
- Readme instructions have been vastly improved ✔️ 
- More consistent error handling has been implemented in controllers ✔️ 
- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2024-05-23 01:03 UTC, closed without merging